name: cd - deploy to eks

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: terraform apply
        working-directory: ./infrastructure
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: deploy api to eks
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: ${{ secrets.ECR_API_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/${{ secrets.K8S_API_DEPLOYMENT }} ${{ secrets.K8S_API_CONTAINER }}=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl rollout status deployment/${{ secrets.K8S_API_DEPLOYMENT }}

      - name: deploy front to eks
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: ${{ secrets.ECR_FRONTEND_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/${{ secrets.K8S_FRONTEND_DEPLOYMENT }} ${{ secrets.K8S_FRONTEND_CONTAINER }}=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl rollout status deployment/${{ secrets.K8S_FRONTEND_DEPLOYMENT }}
