name: ci - workflows

on:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  test-workflows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: validate yaml
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_YAML: true
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ github.token }}

      - name: test workflow changes
        run: |
          echo "workflows have been updated"
